#!/bin/sh

PATH="$PATH:/usr/local/bin:/usr/local/sbin"
export PATH

if [ -e "/opt/settings.conf" ] ; then
  # Check for hard-coded XDMCP host
  if [ -n `grep "^XDMCPHOST=" /opt/settings.conf | cut -d '=' -f 2` ] ; then
    XDMCPHOST=`grep "^XDMCPHOST=" /opt/settings.conf | cut -d '=' -f 2`
  fi
fi

if [ -n "$XDMCPHOST" ] ; then  
 echo "Connecting to XDMCP host: $XDMCPHOST"
  X -query $XDMCPHOST
else
  echo "Searching for XDMCP broadcast servers..."
  X -broadcast
fi
