#!/bin/sh
# Copyright (c) 2007-2015 The OpenRC Authors.
# See the Authors file at the top-level directory of this distribution and
# https://github.com/OpenRC/openrc/blob/master/AUTHORS
#
# This file is part of OpenRC. It is subject to the license terms in
# the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/OpenRC/openrc/blob/master/LICENSE
# This file may not be copied, modified, propagated, or distributed
#    except according to the terms contained in the LICENSE file.

# If $TERM is not set then assume default of cons25
# This gives us a nice colour boot :)
[ -z "$TERM" -o "$TERM" = "dumb" ] && TERM="cons25" && export TERM

# Handle interrupts
trap : SIGINT
trap "echo 'Boot interrupted'; exit 1" SIGQUIT

# Start TrueOS Script
sh /etc/trueos-rc.sh

/sbin/openrc sysinit || exit 1
/sbin/openrc boot || exit 1
/sbin/openrc default

# Load extra services we need
/etc/init.d/modules start
/etc/init.d/devd start
/etc/init.d/moused start
/etc/init.d/network start

# Fix for QT to allow startup without DBUS
if [ ! -e "/var/lib/dbus/machine-id" ] ; then
/usr/local/bin/dbus-uuidgen --ensure
fi

# We don't actually care if rc default worked or not, we should exit 0
# to allow logins

